""" JUST ADDING BASIC FILE TO GITHUB

GOAL PROJECT :
  - CREATE A TIC TAC TOE THAT WORKS AND LOOKS GOOD
  - NO COPYING FULL CODE FROM INTERNET
  - LEARN PYGAMES
  - COMMENT WELL
  - WRITE THE PYTHONIC WAY AND NOT JAVA !!!!!"""